FROM node:20-alpine AS base
WORKDIR /app
COPY api/package.json api/package-lock.json ./api/
RUN cd /app/api && npm ci
COPY api /app/api
WORKDIR /app/api
RUN npm run build
CMD ["node", "dist/index.js"]
